#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/python" ]; then
  "$basedir/python"  "$basedir/modules/not_node/main.js" "$@"
  ret=$?
else
  python  "$basedir/modules/not_node/main.js" "$@"
  ret=$?
fi
exit $ret
